#!/usr/bin/sh

vol="$(pamixer --get-volume)"
mute="$(pamixer --get-mute)"

if [ "$mute" = "true" ]; then
    echo "󰝟"
else
    echo "󰕾 ${vol}%"
fi

case "$1" in
    up) pamixer -i 5 ;;
    down) pamixer -d 5 ;;
    mute) pamixer -t ;;
esac

